<a href="https://colab.research.google.com/github/qkdtnwjd/2026_06_python_CLI_board/blob/main/6_30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# -10 ~10 사이의 정수로 (3,4) 모양의 배열을 만들고 arr1에 저장
arr1 = np.random.randint(-10, 10, (3,4))
print(arr1)

# 아래와 같은 2차원 배열을 만들고 arr2에 저장
arr2 = np.array([
[1,2,3,4],
[5,6,7,8],
[9,10,11,12],
[13,14,15,16]])
print(arr2)

# 1. 각 배열의 차원, 모양, 원소의 갯수를 확인

print(arr1.dtype)
print(arr1.shape)
print(arr1.size)


# 2. arr1에서 행은 모두 출력하고 열은 첫번째, 세번째만 출력
arr1_1 = arr1[::,[0,2]]
print(arr1_1)


# 3. arr2에서 아래처럼 나오게 인덱싱해주세요
print(arr2[1:3,1:3])


# [6, 7]
# [10, 11]

# 4. arr1에서 음수만 출력

print(arr1[arr1<0])

[[ -2  -6   1   9]
 [ -2 -10   8   1]
 [ -2  -6   1  -9]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
int64
(3, 4)
12
[[-2  1]
 [-2  8]
 [-2  1]]
[[ 6  7]
 [10 11]]
[ -2  -6  -2 -10  -2  -6  -9]


In [ ]:

# 연도별 남아, 여아 출생 수
arr =[[1880, 90993, 110491],
[1881, 91954, 100745],
[1882, 107850, 113688],
[1883, 112321, 104629],
[1884, 129022, 114445],
[1885, 133055, 107800],
[1886, 144535, 110784],
[1887, 145982, 101414],
[1888, 178627, 120853],
[1889, 178366, 110584],
[1890, 190377, 111025],
[1891, 185482, 101196],
[1892, 212346, 122037],
[1893, 212906, 112317],
[1894, 222922, 115772],
[1895, 233630, 117398],
[1896, 237920, 119570],
[1897, 234202, 112758],
[1898, 258770, 122693],
[1899, 233023, 106212],
[1900, 299828, 150499],
[1901, 239348, 106471],
[1902, 264077, 122659],
[1903, 261973, 119234],
[1904, 275371, 128125],
[1905, 291629, 132319],
[1906, 295303, 133159],
[1907, 318566, 146833],
[1908, 334313, 154344],
[1909, 347228, 163999],
[1910, 396501, 194218],
[1911, 418299, 225968],
[1912, 558103, 429945],
[1913, 624518, 512557],
[1914, 761548, 654762],
[1915, 983874, 848603],
[1916, 1044323, 890099],
[1917, 1081280, 925511],
[1918, 1157647, 1013537],
[1919, 1130145, 980149],
[1920, 1198283, 1064463],
[1921, 1232999, 1101457],
[1922, 1200919, 1088287],
[1923, 1206330, 1096168],
[1924, 1248876, 1132751],
[1925, 1217352, 1115958],
[1926, 1185304, 1110505],
[1927, 1192330, 1126717],
[1928, 1153117, 1107518],
[1929, 1116422, 1075313],
[1930, 1125761, 1097176],
[1931, 1064497, 1039127],
[1932, 1066994, 1043808],
[1933, 1007710, 991127],
[1934, 1044039, 1032291],
[1935, 1048428, 1040930],
[1936, 1040202, 1036974],
[1937, 1063872, 1066309],
[1938, 1103277, 1108841],
[1939, 1096518, 1106544],
[1940, 1143325, 1158900],
[1941, 1207919, 1227941],
[1942, 1350545, 1380774],
[1943, 1395082, 1426846],
[1944, 1327104, 1362555],
[1945, 1307028, 1345610],
[1946, 1571184, 1623650],
[1947, 1772644, 1829223],
[1948, 1697814, 1754469],
[1949, 1710825, 1773725],
[1950, 1713180, 1790673],
[1951, 1800042, 1881080],
[1952, 1854698, 1944277],
[1953, 1880326, 1969777],
[1954, 1941682, 2037374],
[1955, 1954664, 2057918],
[1956, 2007512, 2113694],
[1957, 2044160, 2155866],
[1958, 2010884, 2120712],
[1959, 2023044, 2133509],
[1960, 2022093, 2132717],
[1961, 2017316, 2122502],
[1962, 1966548, 2068945],
[1963, 1927217, 2031755],
[1964, 1894594, 1993270],
[1965, 1765001, 1861378],
[1966, 1691868, 1783964],
[1967, 1650764, 1744527],
[1968, 1640103, 1738928],
[1969, 1686947, 1789732],
[1970, 1748147, 1859594],
[1971, 1663475, 1769201],
[1972, 1521185, 1622666],
[1973, 1458139, 1559338],
[1974, 1467413, 1573105],
[1975, 1457699, 1562207],
[1976, 1465096, 1569904],
[1977, 1532997, 1643684],
[1978, 1531658, 1642250],
[1979, 1605051, 1721947],
[1980, 1659933, 1783876],
[1981, 1667465, 1790907],
[1982, 1692678, 1813970],
[1983, 1670061, 1791732],
[1984, 1682973, 1803830],
[1985, 1720036, 1847032],
[1986, 1714664, 1840164],
[1987, 1737891, 1865662],
[1988, 1779839, 1912602],
[1989, 1843105, 1999999],
[1990, 1897709, 2052543],
[1991, 1874434, 2019463],
[1992, 1843304, 1996388],
[1993, 1808379, 1960397],
[1994, 1785074, 1931157],
[1995, 1757927, 1902832],
[1996, 1752249, 1893378],
[1997, 1739806, 1884122],
[1998, 1765915, 1910250],
[1999, 1772632, 1918809],
[2000, 1814601, 1962406],
[2001, 1799049, 1941251],
[2002, 1795206, 1939815],
[2003, 1825359, 1973434],
[2004, 1834145, 1982794],
[2005, 1845379, 1994841],
[2006, 1898463, 2052377],
[2007, 1919408, 2072139],
[2008, 1887234, 2036289],
[2009, 1832925, 1979303],
[2010, 1772738, 1913851],
[2011, 1753500, 1893230]]


# 1. 남아, 여아 출생 평균을 구하시오
# 남아 출생 총 합:



i=0
boy=0
while i <=(2011-1880):

  arr[i][1]

  #print(arr[i][1])

  boy+=arr[i][1]
  #print(boy)
  i+=1


print("남아 출생 평균={}명".format(int(boy/(2012-1880)))
)

# 여아 출생 총 합:



i=0
girl=0
while i <=(2011-1880):

  arr[i][2]

  #print(arr[i][2])

  girl+=arr[i][2]

  i+=1


print("여아 출생 평균={}명".format(int(girl/(2012-1880))))


# 2. 남아 출생이 가장 많은 연도와 남아의 수를 구하시오



# 3. 2000년 이후 데이터
i=120
while i<132:
  print(arr[i])

  i+=1





# 4. 1800년대, 1900년대, 2000년대 각 남아 여아 수의 평균을 구하시오


' '

i=1880
boy1800=0
boy1900=0
boy2000=0
while i <=2011:

  arr[(i-1880)][1]

  #print(arr[i][1])
  #1800년대
  if i<1900:

    boy1800+=arr[(i-1880)][1]
   # print(boy1800)


  if 1900<=i<2000:
    boy1900+=arr[i-1880][1]


  if 2000<=i:
    boy2000+=arr[i-1880][1]


  #print(boy)
  i+=1


print("1800년대 남아 출생 평균={}명".format(int(boy1800/(1901-1880))))
print("1900년대 남아 출생 평균={}명".format(int(boy1900/(2001-1900))))
print("2000년대 남아 출생 평균={}명".format(int(boy2000/(2012-2000))))

남아 출생 평균=1225776명
여아 출생 평균=1245399명
[2000, 1814601, 1962406]
[2001, 1799049, 1941251]
[2002, 1795206, 1939815]
[2003, 1825359, 1973434]
[2004, 1834145, 1982794]
[2005, 1845379, 1994841]
[2006, 1898463, 2052377]
[2007, 1919408, 2072139]
[2008, 1887234, 2036289]
[2009, 1832925, 1979303]
[2010, 1772738, 1913851]
[2011, 1753500, 1893230]
1800년대 남아 출생 평균=168299명
1900년대 남아 출생 평균=1349407명
2000년대 남아 출생 평균=1831500명


In [124]:
import pandas as pd
# 읽어올 엑셀 파일 지정
filename = 'pandas_ex.xlsx'

# 엑셀 파일 읽어 오기
df = pd.read_excel(filename, engine='openpyxl')
df

# 읽어올 엑셀 파일 지정
filename = 'pandas_ex.csv'

# 엑셀 파일 읽어 오기
df = pd.read_csv(filename, encoding='euc-kr')
df

# 읽어올 엑셀 파일 지정
filename = 'tested.csv'

# 엑셀 파일 읽어 오기
df = pd.read_csv(filename, encoding='euc-kr')
df.head()


FileNotFoundError: [Errno 2] No such file or directory: 'pandas_ex.xlsx'

In [143]:
#파이썬 심화

print("== CLI 게시판 실행==")

i=1

while True:


  a = input("명령어)")

  if a == "exit":
    ("== CLI 게시판 종료==")
    break



  if a=="article write":

    list = {input("제목)"):input("내용)")}

    print("{}번 글이 생성 되었습니다.".format(i))

    continue



  if a == "article list":


    for t in list :

      k = list[t]


      print("==========================")
      print("번호 / 제목/ 내용")
      print("{} / {} / {}".format(i,t,k))
      print("==========================")



      print("{}번 글이 생성 되었습니다.".format(i))

      break




  i+=1







== CLI 게시판 실행==
명령어)article write
제목)1
내용)2
1번 글이 생성 되었습니다.
명령어)article write
제목)3
내용)4
1번 글이 생성 되었습니다.


KeyboardInterrupt: Interrupted by user